### ISSUE TITLE
Include jetty-maven plugin and upgrade to Jetty 9

### ISSUE THREAD

**Issue by yelzhanzh** [spyropoulosl/simplewebapp.com#5]
Include jetty-maven-plugin to be able run jetty as a maven task rather than running it from IDEA.
When using Jetty from IDEA following issues were discovered: 
- This is difficult to change the default port for Jetty 9; IDEA is still running it on default 8080 port
- When deploying the war to the server there is a need to run mvn:clean; failure doing so results in confusion

**Comment by spyropoulosl** [comment]
If this is done then resolve it please.

**Comment by yelzhanzh** [comment]
Yeap, forgot to do it. Thanks.
resolved now
